name: gwana
region: nyc

services:
  - name: web
    github:
      repo: votre-username/gwana
      branch: main
      deploy_on_push: true
    run_command: bundle exec puma -C config/puma.rb
    environment_slug: ruby
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /up
    envs:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        value: ${RAILS_MASTER_KEY}
        scope: RUN_TIME
        type: SECRET
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
        scope: RUN_TIME
        type: SECRET
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: ACTIVE_STORAGE_SERVICE
        value: digitalocean
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: APP_DOMAIN
        value: ${APP_DOMAIN}
        scope: RUN_TIME

databases:
  - name: db
    engine: PG
    production: false
    version: "15"
  - name: redis
    engine: REDIS
    production: false
    version: "7"

jobs:
  - name: sidekiq
    github:
      repo: votre-username/gwana
      branch: main
    run_command: bundle exec sidekiq
    environment_slug: ruby
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        value: ${RAILS_MASTER_KEY}
        scope: RUN_TIME
        type: SECRET
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
        scope: RUN_TIME
        type: SECRET
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: ACTIVE_STORAGE_SERVICE
        value: digitalocean


